### ISSUE TITLE
token.fastly.com no longer in service

### ISSUE THREAD

**Issue by djchen** [fastly/token-functions#18]
It looks like the token.fastly.com service used in the example code no longer works.
The subdomain returns "Fastly error: unknown domain: token.fastly.com. Please check that this domain has been added to a service."

**Comment by stephenbasile** [comment]
Hi @djchen, the token.fastly.com configuration has been reactivated and should work now. However, I highly recommend you use [the new tokens in the README](https://github.com/fastly/token-functions/blob/master/README.md). They are far more flexible and the expiration time is more granular. If you need any help setting things up, let me know.

**Comment by djchen** [comment]
Thanks!
